package com.udacity.project4.locationreminders.geofence

object GeofenceConstants {

    val REQUEST_BACKGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 33
    val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
    val REQUEST_NOTIFICATION_ONLY_PERMISSIONS_REQUEST_CODE = 35
    val REQUEST_NOTIFICATION_AND_BACKGROUND_PERMISSIONS_REQUEST_CODE= 36
    val REQUEST_TURN_DEVICE_LOCATION_ON = 29
    val BACKGROUND_LOCATION_PERMISSION_INDEX = 1
    val EXTRA_GEOFENCE_INDEX = "GEOFENCE_INDEX"
    val CIRCULAR_REGION_RADIUS = 300f
    val LOCATION_PERMISSION_INDEX = 0
    val ACTION_GEOFENCE_EVENT = "GeofenceConstants.GeofenceEvent"
    val REQUEST_LOCATION_PERMISSION = 1
    val GEOFENCE_REQUEST_ID = "100"
    val EXTRA_REQUEST_ID = "REQUEST_ID"
    val NOTIFICATION_ID = 33
    val CHANNEL_ID = "GeofenceChannel"
}